config/routes.rb
Rails.application.routes.draw do

  resources :clinicians
  resources :patients
  resources :esas_assessments
  resources :prfs_assessments
  resources :users
  resources :sessions
  resources :password_resets
  resources :comments
  resources :notification_settings
  resources :other_symptoms
  resources :care_groups
  resources :notes
  resources :feedbacks
  resources :care_givers
  resources :specialities
  resources :occupations

  get '/information', to: 'pages#landing'

  get '/home', to: 'pages#home'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/agreement', to: 'users#agreement'



  get "/login", to: "sessions#new", :as => "login"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

   get "/info", to: "sessions#information"

  root to: "pages#home"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :clinician
	belongs_to :patient

	validates :patient_id, presence: true
	validates :clinician_id, presence: true
	validates :from, presence: true
	validates :general_comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :require_clinician
  skip_before_action :require_admin

  def index
    if current_clinician
      @comments = current_clinician.comments
    else
      @comments = Patient.find_by(user_id: current_user.id).comments
    end
  end

  def show
    @comment = Comment.find_by(id: params["id"])
    @patient = @comment.patient
    @clinician = @comment.clinician
    @comments = @patient.comments.order("created_at desc")

    if current_clinician
      if @comment.patient.clinicians.include?(current_clinician)
      else
        redirect_to root_path, notice: "You tried to access information you do not have authorization for"
      end
    else
      if @comment.patient.id == current_user.patient.id
      else
        redirect_to root_path, notice: "You tried to access information you do not have authorization for"
      end
    end
  end

  def new
    @comment = Comment.new
    if current_clinician
    else
      @patient = Patient.find_by(id: current_user.patient.id)
      @care_group_assignments = @patient.care_group_assignments
    end

    if current_clinician
      @comments = current_clinician.comments.order("created_at desc")
    else
      @comments = Patient.find_by(user_id: current_user.id ).comments.order("created_at desc")
    end
  end

  def create
    if current_clinician
      @comments = current_clinician.comments
    else
      @comments = Patient.find_by(user_id: User.find_by(id: current_user)).comments
    end

    @comment = Comment.new(comment_params)
    if current_clinician
      @comment.clinician = current_user.clinician
      @comment.from = current_user.clinician.user_id
      if @comment.save

        redirect_to comment_path(@comment), notice: "Comment submitted!"
      else
        render "new", alert: "Comment not submitted!"
      end
    else
      @comment.patient = current_user.patient
      @comment.from = current_user.patient.user_id
      if @comment.save

        redirect_to comment_path(@comment), notice: "Comment submitted!"
      else
        render "new", alert: "Comment not submitted!"
      end
    end
  end


  def edit
    @comment = Comment.find_by(id: params["id"])
    @user = @comment.from
    @clinician = Clinician.find_by(user_id: @user)
    @patient = Patient.find_by(user_id: @user)
  end

  def update
    @comment = Comment.find_by(id: params["id"])
    @comment.update_attributes(comment_params)
    if @comment.valid?
      redirect_to comment_path(@comment), notice: "Comment edited!"
    else
      render "edit", alert: "Comment not edited!"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params["id"])
    @comment.destroy

    redirect_to comments_path, notice: "Comment deleted!"
  end

  private

    def comment_params
      # It's mandatory to specify the nested attributes that should be whitelisted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
      params.require(:comment).permit( :patient_id,:clinician_id,:from,:created_at,:updated_at,:general_comment)
    end

end

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this assessment from being saved:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  <% if @clinician.nil? %>
    Edit comment written by <%= @patient.first_name %> <%= @patient.last_name %> at <%= @comment.created_at.to_s(:long) %> 
  <% else %>
    Edit comment written by <%= @clinician.first_name %> <%= @clinician.last_name %> at <%= @comment.created_at.to_s(:long) %> 
  <% end %>
</h3>

<%= form_for @comment do |form| %>
  <div class="form-group">
    <%= form.label "Between patient:" %>
    <%= form.collection_select :patient_id, Patient.all, :id, :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "And clinician:" %>
    <%= form.collection_select :clinician_id, Clinician.all, :id, :first_name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :general_comment %>
    <%= form.text_area :general_comment, class: "form-control", rows: 5, placeholder: "Leave a comment" %>
  </div>
 
  <%= form.button 'Update Comment', class: "btn btn-u btn-success" %>
<% end %>

app/views/comments/index.html.erb
<!DOCTYPE html>

<head>
    <title>SeeYouNow | Comments</title>
</head>

<h3 class="page-header">
  All Conversations
  <span class="pull-right">
    <%= link_to "New comment", new_comment_path, class: 'btn btn-u btn-success' %>
  </span>
</h3>

<!-- <ul>


  <% @comments.each do |comment| %>
  		<% if current_clinician %>
	    	<li><h4><%= link_to "With #{ comment.patient.first_name } #{ comment.patient.last_name} from #{comment.created_at.to_s(:long)}", comment_path(comment) %><%= time_ago_in_words(comment.created_at) %></h4> 
	    
	    	<%= link_to "Edit", edit_comment_path(comment) %>
	    <% else %>
	    	<li><h4><%= link_to "With #{ comment.clinician.first_name } #{ comment.clinician.last_name} from #{comment.created_at.to_s(:long)}", comment_path(comment) %></h4>
	    <% end %>

	    <%= link_to "Delete", comment_path(comment), method: :delete, data: {confirm: 'Are you sure you want to delete'} %></li>
  <% end %>
</ul> -->

<body>
<!--=== Profile ===-->
    <div class="profile container content">
      <div class="row">
            <div class="col-md-12">
            	<!--Profile Body-->
            	<div class="profile-body">

            		<div class="row margin-bottom-20"><!--start row-->
            		  <!--Conversations-->
            		  <div class="col-sm-5">
            		      <div class="panel panel-profile no-bg">
            		          <div class="panel-heading overflow-h">
            		              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-bed"></i>Conversations</h2>
            		              <a href="#"><i class="fa fa-cog pull-right"></i></a>
            		          </div>
            		          <div id="scrollbar" class="panel-body contentHolder">
            		          <% if current_clinician %>
                            <% @comments.order("patient_id, created_at DESC").select('ON (patient_id) *').uniq.each_with_index do |comment, index| %>
                                <div class="profile-post color-one">
                                    <span class="profile-post-numb"><%= index+1 %></span>
                                    <div class="profile-post-in">
                                        <h3 class="heading-xs"><a><%= link_to "#{comment.patient.first_name} #{comment.patient.last_name}", comment_path(comment) %></a></h3>
                                        <p>Lastest comment from <%= time_ago_in_words(comment.created_at) %> ago<i class="pull-right"><%= link_to "Edit", edit_comment_path(comment) %> <%= link_to "Delete", comment_path(comment), method: :delete, data: {confirm: 'Are you sure you want to delete'} %></i></p>
                                    </div>
                                </div>
                            <% end %>
                          <% else %>
                            <% @comments.order("clinician_id, created_at DESC").select('ON (clinician_id) *').uniq.each_with_index do |comment, index| %>
                                <div class="profile-post color-one">
                                    <span class="profile-post-numb"><%= index+1 %></span>
                                    <div class="profile-post-in">
                                        <h3 class="heading-xs"><a><%= link_to "#{comment.clinician.first_name} #{comment.clinician.last_name}", comment_path(comment) %></a></h3>
                                        <p><%= comment.clinician.occupation.name %></p>
                                    </div>
                                </div>
                            <% end %>
                          <% end %>
            		          </div>
            		      </div>        
            		  </div>
            		  <!--End Conversations-->

                  <!--End Comments Post-->
            		  <div class="col-sm-7">
                      <div class="panel panel-profile">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-comments-o"></i> Comments</h2>
                          </div>
                          <div id="scrollbar4" class="panel-body contentHolder">
                          <% if current_clinician %>
                            <% @comments.order("created_at desc").limit(99).each_with_index do |comment, index| %>
                              <% if comment.from == current_user.id %>
                              <% else %>
                                <div class="comment">
                                    <div class="overflow-h">
                                        <strong><%= link_to "#{comment.patient.first_name} #{comment.patient.last_name}", comment_path(comment) %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong> 
                                        <p><%= comment.general_comment %></p>
                                        <ul class="list-inline comment-list">
                                            <li><i class="fa fa-heartbeat"> </i> <%= comment.patient.diagnosis %></li>
                                        </ul>
                                    </div>    
                                </div>
                              <% end %>
                            <% end %>
                          <% else %>
                            <% @comments.order("created_at desc").limit(99).each_with_index do |comment, index| %>
                              <% if comment.from == current_user.id %>
                              <% else %>
                                <div class="comment">
                                    <div class="overflow-h">
                                        <strong><%= link_to "#{comment.clinician.first_name} #{comment.clinician.last_name}", comment_path(comment) %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong> 
                                        <p><%= comment.general_comment %></p>
                                        <ul class="list-inline comment-list">
                                            <li><i class="fa fa-user-md"> </i> <%= comment.clinician.occupation.name %></li>
                                        </ul>
                                    </div>    
                                </div>
                              <% end %>
                            <% end %>
                          <% end %>
                          </div>
                      </div>    
                  </div><!--End Comments Post-->


            		</div><!--/end row-->
            	</div><!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div><!--/container-->    
    <!--=== End Profile ===-->

</body>
</html>	

app/views/comments/new.html.erb
<head>
    <title>SeeYouNow | New Comment</title>
</head>

<% if @comment.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this assessment from being saved:</h2>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  Write new comment
</h3>

<body>

<!--=== Profile ===-->
    <div class="profile container content">
      <div class="row">
            <div class="col-md-12">
              <!--Profile Body-->
              <div class="profile-body">

                <div class="row margin-bottom-20"><!--start row-->

                  <!--End Comments Post-->
                  <div class="col-sm-7">
                      <div class="panel panel-profile">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-comments-o"></i> Comments</h2>
                          </div>
                          <div id="scrollbar4" class="panel-body contentHolder">
                          <% if current_clinician %>
                            <% @comments.each_with_index do |comment, index| %>
                              <div class="comment">
                                  <div class="overflow-h">
                                    <% if comment.from == comment.patient.user_id %>
                                      <strong><%= comment.patient.first_name %> <%= comment.patient.last_name %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong> 
                                      <p><%= comment.general_comment %></p>
                                      <ul class="list-inline comment-list">
                                          <li><i class="fa fa-heartbeat"></i> <%= comment.patient.diagnosis %></li>
                                      </ul>
                                    <% else %>
                                      <strong><%= comment.clinician.full_name %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong> 
                                      <p><%= comment.general_comment %></p>
                                      <ul class="list-inline comment-list">
                                          <li><i class="fa fa-user-md"></i> <a href="#"><%= comment.clinician.occupation.name %></a></li>
                                      </ul>
                                    <% end %>
                                  </div>    
                              </div>
                            <% end %>
                          <% else %>
                            <% @comments.each_with_index do |comment, index| %>
                              <div class="comment">
                                  <div class="overflow-h">

                                      <strong><%= comment.clinician.full_name %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong> 
                                      <p><%= comment.general_comment %></p>
                                      <ul class="list-inline comment-list">
                                          <li><i class="fa fa-user-md"></i> <a href="#"><%= comment.clinician.occupation.name %></a></li>
                                      </ul>
                                  </div>    
                              </div>
                            <% end %>
                          <% end %>
                          </div>
                      </div>    
                  </div><!--End Comments Post-->
                </div><!--/end row-->
              </div><!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div><!--/container-->    
    <!--=== End Profile ===-->




<% if current_clinician %>

  <%= form_for @comment do |form| %>
    <div class="form-group">
      <%= form.label :patient_id %>
      <%= form.collection_select :patient_id, current_clinician.patients.order("first_name asc"), :id, :full_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :general_comment %>
      <%= form.text_area :general_comment, class: "form-control", rows: 5, placeholder: "Leave a comment" %>
    </div>

    <%= form.button 'Submit Comment', class: "btn btn-success" %>
  <% end %>

<% else %>

  <%= form_for @comment do |form| %>

    <div class="form-group">
      <%= form.label :clinician_id %>
      <%= form.collection_select :clinician_id, @patient.clinicians.order("first_name asc"), :id, :full_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :general_comment %>
      <%= form.text_area :general_comment, class: "form-control", rows: 5, placeholder: "Leave a comment.  Your comment will only be visible to the clinician you select" %>
    </div>

    <%= form.button 'Submit Comment', class: "btn btn-u btn-success" %>
  <% end %>
  
<% end %>

</body>

app/views/comments/show.html.erb
<head>
    <title>SeeYouNow | Comments</title>
</head>

<h3 class="page-header">
  <% if current_clinician %>
    Conversation wth <%= link_to @patient.full_name, patient_path(@patient.id) %>
  <% else %>
    Conversation wth <%= link_to @clinician.full_name, clinician_path(@clinician.id) %>
  <% end %>
  <span class="pull-right">
    <%= link_to "New comment", new_comment_path, class: 'btn btn-u btn-success' %>
  </span>
</h3>

<body>
<!--=== Profile ===-->
    <div class="profile container content">
      <div class="row">
            <div class="col-md-12">
              <!--Profile Body-->
              <div class="profile-body">

                <div class="row margin-bottom-20"><!--start row-->
                  
                  <!--End Comments Post-->
                  <div class="col-sm-7">
                      <div class="panel panel-profile">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-comments-o"></i> Comments</h2>
                          </div>
                          <div id="scrollbar4" class="panel-body contentHolder">
                            <% @comments.each_with_index do |comment, index| %>
                              <% if comment.clinician == @clinician %>
                                <div class="comment">
                                    <div class="overflow-h">
                                      <% if comment.from == comment.patient.user_id %>
                                        <strong><%= link_to "#{comment.patient.first_name} #{comment.patient.last_name}", comment_path(comment) %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong>
                                      <% else %>
                                        <strong><%= link_to "#{comment.clinician.full_name }", comment_path(comment) %><small class="pull-right"> <%= time_ago_in_words(comment.created_at) %></small></strong>
                                      <% end %>
                                          <p><%= comment.general_comment %></p>
                                    </div>    
                                </div>
                              <% end %>
                            <% end %>
                          </div>
                      </div>    
                  </div><!--End Comments Post-->


                </div><!--/end row-->
              </div><!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div><!--/container-->    
    <!--=== End Profile ===-->

</body>
</html> 