config/routes.rb
Rails.application.routes.draw do

  resources :clinicians
  resources :patients
  resources :esas_assessments
  resources :prfs_assessments
  resources :users
  resources :sessions
  resources :password_resets
  resources :comments
  resources :notification_settings
  resources :other_symptoms
  resources :care_groups
  resources :notes
  resources :feedbacks
  resources :care_givers
  resources :specialities
  resources :occupations

  get '/information', to: 'pages#landing'

  get '/home', to: 'pages#home'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/agreement', to: 'users#agreement'



  get "/login", to: "sessions#new", :as => "login"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

   get "/info", to: "sessions#information"

  root to: "pages#home"

end

app/models/clinician.rb
class Clinician < ActiveRecord::Base
  #acts_as_messageable
	belongs_to :care_group
  has_many :comments
  has_many :notes
	belongs_to :gender
	has_many :patients , through: :care_group_assignments
  has_many :care_group_assignments
  has_many :esas_assessments, :through => :patients
  has_many :prfs_assessments, :through => :patients
	belongs_to :occupation
  belongs_to :speciality
	belongs_to :user
  accepts_nested_attributes_for :user,  :allow_destroy => true

  def full_name
    if occupation.pronym.nil?
      if occupation.acronym.nil?
        first_name + " " + last_name
      else
        first_name + " " + last_name + ", " + occupation.acronym
      end
    else
      occupation.pronym + " " + first_name + " " + last_name
    end
  end

  	validates :first_name, presence: true
  	validates :last_name, presence: true
  	validates :occupation_id, presence: true
  	validates :gender_id, presence: true
  	validates :office_number, presence: true
  	validates :mobile_number, presence: true
end

app/controllers/clinicians_controller.rb
class CliniciansController < ApplicationController
  skip_before_action :require_clinician, only: [:show]
  skip_before_action :require_admin, only: [:show, :edit]

  def index
    @current_group = current_clinician.care_group_id
    # @clinicians = Clinician.where.not(first_name: "System").order("care_group_id asc")
    # @care_groups = CareGroup.where.not(name: "System Admin").order("province asc")
    @clinicians = Clinician.where.not(care_group_id: "162,163").order("care_group_id desc")
    @care_groups = CareGroup.where.not(name: "Brameast").order("name asc")
  end

  def show
    @clinician = Clinician.find_by(id: params["id"])
    @patients = @clinician.patients.group(:patient_deceased).count
    @current_patients = @patients.values[0]
    @past_patients = @patients.values[1]
  end

  def new
    @clinician = Clinician.new
    @user = User.new
    @clinician.build_user
  end

  def create
    @clinician = Clinician.create(clinician_params)
    
    if @clinician.save
      redirect_to clinician_path(@clinician), notice: "Clinician created!"
    else
      render "new"
    end
  end

  def edit
    @clinician = Clinician.find_by(id: params["id"])
  end

  def update
    @clinician = Clinician.find_by(id: params["id"])
    @clinician.update_attributes(clinician_params)
    if @clinician.valid?
      redirect_to clinician_path(@clinician), notice: "Clinician information edited!"
    else
      render "edit"
    end
  end

  def destroy
    @clinician = Clinician.find_by(id: params["id"])
    @clinician.destroy
    redirect_to clinicians_path, notice: "Clinician deleted!"
  end

  private

    def clinician_params
      # It's mandatory to specify the nested attributes that should be whitelisted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
      params.require(:clinician).permit(:first_name,:last_name,:occupation_id, :speciality_id,:gender_id, :office_number, :mobile_number, :emergency_message, :care_group_id, :administrator, :user_id, user_attributes: [ :email, :password, :patient_id, :clinician_id, :terms_agreement ])
    end

end

app/views/clinicians/edit.html.erb
<head>
    <title>SeeYouNow | Edit Clinician</title>
</head> 

<% if @clinician.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this clinician from being saved:</h2>
    <ul>
      <% @clinician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  Edit information for <%= @clinician.full_name %>
</h3>

<div class="profile container content">
  <div class="centre">
    <div class="col-md-8">
      <!--Profile Body-->
      <div class="profile-body">

        <%= form_for @clinician do |form| %>
          <div class="form-group">
            <%= form.label :first_name %>
            <%= form.text_field :first_name, class: "form-control", placeholder: "First name" %>
          </div>

          <div class="form-group">
            <%= form.label :last_name %>
            <%= form.text_field :last_name, class: "form-control", placeholder: "Last name" %>
          </div>

          <div class="form-group">
            <%= form.label :occupation_id %>
            <%= form.collection_select :occupation_id, Occupation.all, :id, :name, { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :speciality_id %>
            <%= form.grouped_collection_select :speciality_id, Occupation.order(:name), :specialities, :name,  :id, :name, { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :gender_id %>
            <%= form.collection_select :gender_id, Gender.all, :id, :gender_type, { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :office_number %>
            <%= form.text_field :office_number, class: "form-control", placeholder: "Office number" %>
          </div>

          <div class="form-group">
            <%= form.label "Number to call oncall physician out of office hours" %>
            <%= form.text_field :mobile_number, class: "form-control", placeholder: "Oncall contact number" %>
          </div>

          <div class="form-group">
            <%= form.label :care_group_id %>
            <%= form.collection_select :care_group_id, CareGroup.all, :id, :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :administrator %>
            <%= form.check_box :administrator %>
          </div>
          <%= form.button 'Update Clinician', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clinicians/index.html.erb
<head>
    <title>SeeYouNow | Clinician Index</title>
</head>	

<h3 class="page-header">
  Manage Clinicians
  <span class="pull-right">
    <%= link_to "New Clinician", new_clinician_path, class: 'btn btn-u btn-success' %>
  </span>
</h3>
<h4 span class="time">
    <span class="pull-right">
    <%= link_to "New Care Group", new_care_group_path, class: 'btn btn-u btn-success' %>
    </span>
</h4>

<body>
<!--=== Profile ===-->
    <div class="profile container content">
      <div class="row">
            <div class="col-md-12">
            	<!--Profile Body-->
            	<div class="profile-body">

            		<div class="row margin-bottom-20"><!--start row-->
            		  <!--Clinicians list-->
            		  <div class="col-sm-6">
            		      <div class="panel panel-profile no-bg">
            		          <div class="panel-heading overflow-h">
            		              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-bed"></i>Clinicians You Are Managing</h2>
            		              <a href="#"><i class="fa fa-cog pull-right"></i></a>
            		          </div>
            		          <div id="scrollbar" class="panel-body contentHolder">
            		          
            		          <% @clinicians.each_with_index do |clinician, index| %>
            		              <div class="profile-post color-one">
            		                  <span class="profile-post-numb"><%= index+1 %></span>
            		                  <div class="profile-post-in">
            		                      <h3 class="heading-xs"><a><%= link_to clinician.full_name, clinician_path(clinician) %></a></h3>
            		                      <p><%= clinician.occupation.name %>, <%= clinician.care_group.name %><i class="pull-right"><%= link_to "Edit", edit_clinician_path(clinician) %> <%= link_to "Delete", clinician_path(clinician), method: :delete, data: {confirm: 'Are you sure you want to delete'} %></i></p>
            		                  </div>
            		              </div>
            		          <% end %>
            		          </div>
            		      </div>        
            		  </div>
            		  <!--End Clinicians list-->

            		  <!--Care Groups-->
            		  <div class="col-sm-6">
            		      <div class="panel panel-profile no-bg">
            		          <div class="panel-heading overflow-h">
            		              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-bed"></i>Care Groups</h2>
            		              <a href="#"><i class="fa fa-cog pull-right"></i></a>
            		          </div>
            		          <div id="scrollbar" class="panel-body contentHolder">
            		          
            		          <% @care_groups.each_with_index do |care_group, index| %>
            		              <div class="profile-post color-one">
            		                  <span class="profile-post-numb"><%= index+1 %></span>
            		                  <div class="profile-post-in">
            		                      <h3 class="heading-xs"><a><%= link_to "#{care_group.name}", care_group_path(care_group) %></a></h3>
            		                      <p><%= care_group.city %>, <%= care_group.province %> <i class="pull-right"><%= link_to "Edit", edit_care_group_path(care_group) %> <%= link_to "Delete", care_group_path(care_group), method: :delete, data: {confirm: 'Are you sure you want to delete'} %></i></p>
            		                  </div>
            		              </div>
            		          <% end %>
            		          </div>
            		      </div>        
            		  </div>
            		  <!--End Care Groups-->

            		</div><!--/end row-->
            	</div><!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div><!--/container-->    
    <!--=== End Profile ===-->

</body>

app/views/clinicians/new.html.erb
<head>
    <title>SeeYouNow | New Clinician</title>
</head> 

<% if @clinician.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this clinician from being saved:</h2>
    <ul>
      <% @clinician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  Create New Clinician
</h3>

<div class="profile container content">
  <div class="centre">
    <div class="col-md-8">
      <!--Profile Body-->
      <div class="profile-body">

        <%= form_for @clinician do |form| %>

          <%= form.fields_for :user do |builder| %>
            <div class="form-group">
              <%= builder.label :email %>
              <%= builder.text_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= builder.label :password %>
              <%= builder.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= builder.label :password_confirmation %>
              <%= builder.password_field :password_confirmation, class: "form-control" %>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :first_name %>
            <%= form.text_field :first_name, class: "form-control", placeholder: "First name" %>
          </div>

          <div class="form-group">
            <%= form.label :last_name %>
            <%= form.text_field :last_name, class: "form-control", placeholder: "Last name" %>
          </div>

          <div class="form-group">
            <%= form.label :occupation_id %>
            <%= form.collection_select :occupation_id, Occupation.all, :id, :name, { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :speciality_id %>
            <%= form.grouped_collection_select :speciality_id, Occupation.order(:name), :specialities, :name,  :id, :name, { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :gender_id %>
            <%= form.collection_select :gender_id, Gender.all, :id, :gender_type, { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :office_number %>
            <%= form.text_field :office_number, class: "form-control", placeholder: "Office number" %>
          </div>

          <div class="form-group">
            <%= form.label "Number to call oncall physician out of office hours" %>
            <%= form.text_field :mobile_number, class: "form-control", placeholder: "Oncall contact number" %>
          </div>

          <div class="form-group">
            <%= form.label :care_group_id %>
            <%= form.collection_select :care_group_id, CareGroup.all, :id, :name, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :administrator %>
            <%= form.check_box :administrator %>
          </div>
          
          <%= form.button 'Create Clinician', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clinicians/show.html.erb
<!-- Use view helpers (e.g. link_to and image_tag) -->
<!-- and implement real data -->

<head>
    <title>SeeYouNow | Clinician Profile </title>
</head> 

<h1 class="page-header">
  <%= @clinician.full_name %>
  <span class="pull-right">
    <%= link_to "Edit", edit_clinician_path, class: 'btn btn-u btn-success' %>
  </span>
</h1>
 <h3 span class="diagnosis"><%= @clinician.occupation.name %>
  <% if @clinician.speciality == nil %>
  <% else %>
    , <%= @clinician.speciality.name %></span>
  <% end%>
</h3>


<body>
<!--=== Profile ===-->
    <div class="profile container content">
      <div class="row">
            <div class="col-md-12">
              <!--Profile Body-->
              <div class="profile-body">

                <div class="row margin-bottom-10"><!--start row-->

                  <!--=== Goals of Care Block ===-->
                  <div class="bg-color-light">
                      <div class="container content">
                        <div class="row">
                        <div class="col-md-11">
                          <div class="headline-center margin-bottom-10">
                              <h2>Emergency Message</h2>
                              <p><%= @clinician.care_group.emergency_message %></p>
                          </div>
                        </div>        
                        </div>
                      </div>
                  </div>
                  <!--=== End Goals of Care Block ===-->

                  <!--Patient Information-->
                  <div class="col-sm-6">
                      <div class="panel panel-profile no-bg">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-user-md"></i>Clinician Information</h2>
                          </div>
                          <div id="scrollbar" class="panel-body contentHolder">
                                <div class="profile-post color-one">
                                    <span class="profile-post-numb"></span>
                                    <div class="profile-post-in">
                                        <p><strong>Occupation:</strong> <%= @clinician.occupation.name %></p>
                                        <% if @clinician.speciality == nil %>
                                        <% else %>
                                          <p><strong>Speciality:</strong> <%= @clinician.speciality.name %></p>
                                        <% end%>
                  <% if current_clinician %>
                                        <p><strong>Gender:</strong> <%= @clinician.gender.gender_type %></p>
                                        <p><strong>Email:</strong> <%= User.find_by(id: @clinician.user_id).email %></p>
                                        <p><strong>Office number:</strong> <%= @clinician.office_number %></p>
                                        <p><strong>Mobile number:</strong> <%= @clinician.mobile_number %></p>
                                    </div>
                                </div>
                          </div>
                      </div>        
                  </div>
                  <!--End Patient Information-->

                  <!--Administrative Information-->
                  <div class="col-sm-6">
                      <div class="panel panel-profile no-bg">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-hospital-o"></i>Administrative Information</h2>
                          </div>
                          <div id="scrollbar" class="panel-body contentHolder">
                                <div class="profile-post color-one">
                                    <span class="profile-post-numb"></span>
                                    <div class="profile-post-in">
                                        <p><strong>Care Group</strong>
                                        <p><%= @clinician.care_group.name %></p>
                                    </div>
                                    <span class="profile-post-numb"></span>
                                    <div class="profile-post-in">
                                        <p><strong>Current SeeYouNow Patients</strong>
                                        <p><%= @current_patients %></p>
                                    </div>
                                    <span class="profile-post-numb"></span>
                                    <div class="profile-post-in">
                                        <p><strong>Archived Patients</strong>
                                        <p><%= @past_patients %></p>
                                    </div>
                                </div>
                          </div>
                      </div>        
                  </div>
                  <!--End Administrative Information-->

                  <% else %>
                                    </div>
                                </div>
                          </div>
                      </div>        
                  </div>
                  <!--End Patient Information-->

                  <% end %>

                </div><!--/end row-->
              </div><!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div><!--/container-->    
    <!--=== End Profile ===-->

</body>