config/routes.rb
Rails.application.routes.draw do

  resources :clinicians
  resources :patients
  resources :esas_assessments
  resources :prfs_assessments
  resources :users
  resources :sessions
  resources :password_resets
  resources :comments
  resources :notification_settings
  resources :other_symptoms
  resources :care_groups
  resources :notes
  resources :feedbacks
  resources :care_givers
  resources :specialities
  resources :occupations

  get '/information', to: 'pages#landing'

  get '/home', to: 'pages#home'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/agreement', to: 'users#agreement'



  get "/login", to: "sessions#new", :as => "login"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

   get "/info", to: "sessions#information"

  root to: "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_one :patient, :dependent => :destroy
  has_one :clinician, :dependent => :destroy
  accepts_nested_attributes_for :patient,  :allow_destroy => true 
  accepts_nested_attributes_for :clinician,  :allow_destroy => true
  has_many :feedbacks
  
  validates :password,
  	:length => { :minimum => 6 }, :if => :password_digest_changed?
  validates_presence_of     :password, on: :create

  before_validation(on: :update) do
    # only want confirmation validation to run if user enters password
    self.password_confirmation = nil unless self.password.present?
  end

  # validates_uniqueness_of :email

  before_create { generate_token(:auth_token) }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_user, only: [:new]
  skip_before_action :require_clinician, only: [:edit, :update, :agreement]
  skip_before_action :require_admin, only: [:edit, :update, :agreement]
  skip_before_action :require_agreement, only: [:agreement]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params["id"])
  end

  def new
    @user = User.new
    @patient = Patient.new
    @user.build_patient
  end

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to user_path(@user), notice: "User created!"
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params["id"])
  end

  def agreement
    @user = current_user
  end

  def update
    @user = User.find_by(id: params["id"])
    @user.update(user_params)
    redirect_to root_path, notice: "User updated!"
  end

  def destroy
    @user = User.find_by(id: params["id"])
    @user.destroy
    redirect_to users_path
  end


  private

    def user_params
      # It's mandatory to specify the nested attributes that should be whitelisted.
      # If you use `permit` with just the key that points to the nested attributes hash,
      # it will return an empty hash.
      params.require(:user).permit(:email, :password, :password_confirmation, :auth_token, :password_reset_token, :password_reset_sent_at, :terms_agreement)
    end

end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label "Email or Username" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "User agrees to the " %>
    <a href="/terms" target="_blank">Terms of Service - Platform User Agreement </a>
    <%= form.check_box :terms_agreement %>
  </div> 

  <%= form.button 'Update User', class: "btn btn-success" %>
<% end %>

app/views/users/new.html.erb
<head>
    <title>SeeYouNow | New User</title>
</head> 


<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  Create New User
</h3>

<div class="profile container content">
  <div class="centre">
    <div class="col-md-8">
      <!--Profile Body-->
      <div class="profile-body">

        <%= form_for @user do |form| %>
          <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :password %>
            <%= form.password_field :password, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label "User agrees to the terms" %>
            <a href="/terms">Terms of Service - Platform User Agreement</a>
            <%= form.check_box :terms_agreement %>
          </div>        
          <%= form.button 'Sign Up', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<head>
    <title>SeeYouNow | User</title>
</head>	

<h2 class="page-header">
  User details
  <span class="pull-right">
    <%= link_to "Edit", edit_user_path, class: 'btn btn-u btn-success' %>
  </span>
</h2>
Email/Username: <strong><%= @user.email %></strong> 
    	<% if @user.patient == nil %>
    		<p>Name: <%= link_to @user.clinician.full_name, clinician_path(@user.clinician) %>, Care group: <%= link_to @user.clinician.care_group.name, care_group_path(@user.clinician.care_group) %></p>
        <p>Agreed to Provider Agreement: <%= @user.terms_agreement %></p>
    	<% else %>
    		<p>Name: <%= link_to @user.patient.full_name, patient_path(@user.patient) %>, Care group: <%= link_to @user.patient.care_group.name, care_group_path(@user.patient.care_group) %></p>
        <p>Agreed to User Agreement: <%= @user.terms_agreement %></p>
    	<% end %>