config/routes.rb
Rails.application.routes.draw do

  resources :clinicians
  resources :patients
  resources :esas_assessments
  resources :prfs_assessments
  resources :users
  resources :sessions
  resources :password_resets
  resources :comments
  resources :notification_settings
  resources :other_symptoms
  resources :care_groups
  resources :notes
  resources :feedbacks
  resources :care_givers
  resources :specialities
  resources :occupations

  get '/information', to: 'pages#landing'

  get '/home', to: 'pages#home'
  get '/terms', to: 'pages#terms'
  get '/privacy', to: 'pages#privacy'
  get '/agreement', to: 'users#agreement'



  get "/login", to: "sessions#new", :as => "login"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

   get "/info", to: "sessions#information"

  root to: "pages#home"

end

app/models/prfs_assessment.rb
class PrfsAssessment < ActiveRecord::Base
  belongs_to :clinician
  belongs_to :patient
  belongs_to :care_giver
end

app/controllers/prfs_assessments_controller.rb
class PrfsAssessmentsController < ApplicationController
  skip_before_action :require_clinician, only: [:new, :create, :show, :edit, :update]
  skip_before_action :require_admin

  def index
    if current_clinician
      @prfs_assessments = current_clinician.prfs_assessments
    else
      @prfs_assessments = Patient.find_by(user_id: User.find_by(id: current_user)).prfs_assessments.order("created_at desc")
    end
  end

  def show
    @prfs_assessment = PrfsAssessment.find_by(id: params["id"])
    @care_giver = @prfs_assessment.care_giver

    if current_clinician
      if @prfs_assessment.patient.clinicians.include?(current_clinician)
      else
        redirect_to root_path, notice: "You tried to access information you do not have authorization for"
      end
    else
      if @prfs_assessment.patient.id == current_user.patient.id
      else
        redirect_to root_path, notice: "You tried to access information you do not have authorization for"
      end
    end
  end

  def new
    @prfs_assessment = PrfsAssessment.new
    @select_options = {'normal with no limitations' => ['0'], 'not my normal self, but able to be up and about with fairly normal activities' => ['1'], 'not feeling up to most things, but in bed or chair less than half the day' => ['2'], 'able to do little activity & spend most of the day in bed or chair' => ['3'], 'pretty much bedridden, rarely out of bed' => ['4']}
  end

  def create
    @prfs_assessment = PrfsAssessment.new(prfs_assessment_params)
    if current_clinician
      @prfs_assessment.clinician = current_clinician
      @prfs_assessment.clinician_completed = true
    else
      @prfs_assessment.patient = current_user.patient
      @prfs_assessment.clinician = current_user.patient.clinicians.first
      @prfs_assessment.clinician_completed = false
    end
    if @prfs_assessment.save
      if current_clinician
        redirect_to prfs_assessments_path, notice: "PRFS assessment submitted!"
      else
        redirect_to prfs_assessment_path(@prfs_assessment), notice: "PRFS assessment submitted!"
      end
    else
      render "new", alert: "PRFS assessment not submitted!"
    end
  end

  def edit
    @prfs_assessment = PrfsAssessment.find_by(id: params["id"])
    @select_options = {'normal with no limitations' => ['0'], 'not my normal self, but able to be up and about with fairly normal activities' => ['1'], 'not feeling up to most things, but in bed or chair less than half the day' => ['2'], 'able to do little activity & spend most of the day in bed or chair' => ['3'], 'pretty much bedridden, rarely out of bed' => ['4']}
  end

  def update
    @prfs_assessment = PrfsAssessment.find_by(id: params["id"])
    @prfs_assessment.update_attributes(prfs_assessment_params)
    if @prfs_assessment.valid?
      redirect_to prfs_assessment_path(@prfs_assessment), notice: "PRFS assessment edited!"
    else
      render "edit", alert: "PRFS assessment not edited!"
    end
  end

  def destroy
    @prfs_assessment = PrfsAssessment.find_by(id: params["id"])    
    @prfs_assessment.destroy

    redirect_to prfs_assessments_path, notice: "PRFS assessment deleted!"
  end

  private
    def prfs_assessment_params
      params.require(:prfs_assessment).permit(:patient_id, :clinician_id,:clinician_completed, :created_at, :updated_at, :care_giver_id, :activity_and_function, :prfs_comment)
    end

end

app/views/prfs_assessments/edit.html.erb
<head>
    <title>SeeYouNow | Edit PRFS</title>
</head>

<% if @prfs_assessment.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this assessment from being saved:</h2>
    <ul>
      <% @prfs_assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  Edit PRFS assessment done at <%= @prfs_assessment.updated_at.to_s(:long) %> for <%= @prfs_assessment.patient.first_name %> <%= @prfs_assessment.patient.last_name %>
</h3>

<div class="profile container content">
  <div class="centre">
    <div class="col-md-8">
      <!--Profile Body-->
      <div class="profile-body">

        <%= bootstrap_form_for(@prfs_assessment, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-8") do |form| %>
          
          <% if current_clinician %>
          <% else %>
            <p>Select the care giver that is inputting this assesment</p>

            <div class="form-group">
              <%= form.collection_select :care_giver_id, CareGiver.where(patient_id: current_user.patient.id).order("first_name asc"), :id, :full_name, {:include_blank => "Self completed by patient"}, class: "form-control", control_col: "col-sm-6" %>
            </div>
            <span class="pull-right">
              <%= link_to "Add Care Giver", new_care_giver_path, class: 'btn btn-u btn-success' %>
            </span>
          <% end %>

          <hr style="margin-top: 1px; margin-bottom: 6px;" />

          <div class="form-group">
            <%= form.select :activity_and_function, @select_options, class: "form-control", control_col: "col-sm-2" %>
          </div>

          <div class="form-group">
            <%= form.text_field :prfs_comment, class: "form-control", label: "PRFS Comment", placeholder: "Leave a comment" %>
          </div>
          
          <%= form.button 'Update PRFS assessment', class: "btn btn-u btn-success" %>
        <% end %>
      </div><!--End Profile Body-->
    </div>
  </div><!--/end centre-->
</div><!--/container-->

app/views/prfs_assessments/index.html.erb
<!DOCTYPE html>

<head>
    <title>SeeYouNow | PRFS Assessments</title>
</head>

<h3 class="page-header">
  All PRFS assessments
  <span class="pull-right">
    <%= link_to "New PRFS assessments", new_prfs_assessment_path, class: 'btn btn-u btn-success' %>
  </span>
</h3>

<body>
<!--=== Profile ===-->
    <div class="profile container content">
      <div class="row">
            <div class="col-md-12">
              <!--Profile Body-->
              <div class="profile-body">

                <div class="row margin-bottom-20"><!--start row-->
                  <!--Conversations-->
                  <div class="col-sm-5">
                      <div class="panel panel-profile no-bg">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-bed"></i>Most Recent from each Patient</h2>
                              <a href="#"><i class="fa fa-cog pull-right"></i></a>
                          </div>
                          <div id="scrollbar" class="panel-body contentHolder">
                          <% if current_clinician %>
                            <% @prfs_assessments.order("prfs_assessments.patient_id, prfs_assessments.created_at DESC").select('ON (prfs_assessments.patient_id) *').uniq.each_with_index do |prfs_assessment, index| %>
                                <div class="profile-post color-one">
                                    <span class="profile-post-numb"><%= index+1 %></span>
                                    <div class="profile-post-in">
                                        <h3 class="heading-xs"><a><%= link_to "#{prfs_assessment.patient.first_name} #{prfs_assessment.patient.last_name}", prfs_assessment_path(prfs_assessment) %></a></h3>
                                        <p>Lastest PRFS Assessment from <%= time_ago_in_words(prfs_assessment.created_at) %> ago<i class="pull-right"><%= link_to "Edit", edit_prfs_assessment_path(prfs_assessment) %> <%= link_to "Delete", prfs_assessment_path(prfs_assessment), method: :delete, data: {confirm: 'Are you sure you want to delete'} %></i></p>
                                    </div>
                                </div>
                            <% end %>
                          <% else %>
                            <% @prfs_assessments.group(:clinician_id, :"prfs_assessments.id").each_with_index do |prfs_assessment, index| %>
                                <div class="profile-post color-one">
                                    <span class="profile-post-numb"><%= index+1 %></span>
                                    <div class="profile-post-in">
                                        <h3 class="heading-xs"><a><%= link_to "#{prfs_assessment.clinician.first_name} #{prfs_assessment.clinician.last_name}", prfs_assessment_path(prfs_assessment) %></a></h3>
                                        <p><%= prfs_assessment.clinician.occupation.name %></p>
                                    </div>
                                </div>
                            <% end %>
                          <% end %>
                          </div>
                      </div>        
                  </div>
                  <!--End Conversations-->

                  <!--End Comments Post-->
                  <div class="col-sm-7">
                      <div class="panel panel-profile">
                          <div class="panel-heading overflow-h">
                              <h2 class="panel-title heading-sm pull-left"><i class="fa fa-line-chart"></i>PRFS Assessments</h2>
                          </div>
                          <div id="scrollbar4" class="panel-body contentHolder">
                          <% if current_clinician %>
                            <% @prfs_assessments.order("created_at desc").limit(99).each_with_index do |prfs_assessment, index| %>
                                <div class="comment">
                                    <div class="overflow-h">
                                        <strong><%= link_to "#{prfs_assessment.patient.first_name} #{prfs_assessment.patient.last_name}", prfs_assessment_path(prfs_assessment) %><small class="pull-right"> <%= time_ago_in_words(prfs_assessment.created_at) %></small></strong> 
                                        <p>Activity and Function: <%= prfs_assessment.activity_and_function %>, 
                                        <% if prfs_assessment.prfs_comment == nil %>
                                        <% else %>
                                            Comment: <%= prfs_assessment.prfs_comment %>,
                                        <% end %>
                                        <ul class="list-inline comment-list">
                                            <li><i class="fa fa-heartbeat"> </i> <%= prfs_assessment.patient.diagnosis %></li>
                                        </ul>
                                    </div>    
                                </div>
                            <% end %>
                          <% else %>
                            <% @prfs_assessments.order("created_at desc").limit(99).each_with_index do |prfs_assessment, index| %>
                                <div class="comment">
                                    <div class="overflow-h">
                                        <strong><%= link_to "#{prfs_assessment.clinician.first_name} #{prfs_assessment.clinician.last_name}", comment_path(prfs_assessment) %><small class="pull-right"> <%= time_ago_in_words(prfs_assessment.created_at) %></small></strong> 
                                        <p>Activity and Function: <%= prfs_assessment.activity_and_function %>, 
                                        <% if prfs_assessment.prfs_comment == nil %>
                                        <% else %>
                                            Comment: <%= prfs_assessment.prfs_comment %>,
                                        <% end %>
                                        <ul class="list-inline comment-list">
                                            <li><i class="fa fa-user-md"> </i> <%= prfs_assessment.clinician.occupation.name %></li>
                                        </ul>
                                    </div>    
                                </div>
                            <% end %>
                          <% end %>
                          </div>
                      </div>    
                  </div><!--End Comments Post-->


                </div><!--/end row-->
              </div><!--End Profile Body-->
            </div>
        </div><!--/end row-->
    </div><!--/container-->    
    <!--=== End Profile ===-->

</body>
</html>

app/views/prfs_assessments/new.html.erb
<head>
    <title>SeeYouNow | New PRFS</title>
</head>

<% if @prfs_assessment.errors.any? %>
  <div class="alert alert-warning">
    <h2>Some errors kept this assessment from being saved:</h2>
    <ul>
      <% @prfs_assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3 class="page-header">
  Patient Reported Functional Status (PRFS) Tool
</h3>
<h4 span class="diagnosis">
  Over the past month generally rate patient's activity.  This should be preformed after completing an ESAS Assessment.
</h4>

<div class="profile container content">
  <div class="centre">
    <div class="col-md-8">
      <!--Profile Body-->
      <div class="profile-body">

        <%= bootstrap_form_for(@prfs_assessment, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-8") do |form| %>

          <% if current_clinician %>
            <div class="form-group">
              <%= form.collection_select :patient_id, current_clinician.patients.where(patient_archived: false).order("first_name asc"), :id, :full_name, class: "form-control", control_col: "col-sm-6", label: "Select Patient" %>
            </div>
          <% end %>

          <% if current_clinician %>
          <% else %>
            <p>Select the care giver that is inputting this assesment</p>

            <div class="form-group">
              <%= form.collection_select :care_giver_id, CareGiver.where(patient_id: current_user.patient.id).order("first_name asc"), :id, :full_name, {:include_blank => "Self completed by patient"}, class: "form-control", control_col: "col-sm-6" %>
            </div>
            <span class="pull-right">
              <%= link_to "Add Care Giver", new_care_giver_path, class: 'btn btn-u btn-success' %>
            </span>
          <% end %>

          <hr style="margin-top: 1px; margin-bottom: 6px;" />

          <div class="form-group">
            <%= form.select :activity_and_function, @select_options, class: "form-control", control_col: "col-sm-2" %>
          </div>

          <div class="form-group">
            <%= form.text_field :prfs_comment, class: "form-control", label: "PRFS Comment", placeholder: "Leave a comment" %>
          </div>

          <%= form.button 'Submit PRFS assessment', class: "btn btn-u btn-success" %>
        <% end %>
      </div><!--End Profile Body-->
    </div>
  </div><!--/end centre-->
</div><!--/container--> 

app/views/prfs_assessments/show.html.erb
<!-- Use view helpers (e.g. link_to and image_tag) -->
<!-- and implement real data -->

<head>
    <title>SeeYouNow | PRFS Assessment</title>
</head>

<h4 class="page-header">
  <p><strong>Patient:</strong> <%= link_to "#{@prfs_assessment.patient.first_name} #{@prfs_assessment.patient.last_name}", patient_path(@prfs_assessment.patient) %></p>
  <% if current_clinician %>
    <span class="pull-right">
    <%= link_to "Edit", edit_prfs_assessment_path, class: 'btn btn-u btn-success' %>
    </span>
  <% end %>
  <p><strong>Care Group:</strong> <%= @prfs_assessment.clinician.care_group.name %></p>
</h4>
<h4 span class="time"><strong>Completed:</strong> <%= @prfs_assessment.updated_at.strftime("%B %d, %Y") %> at <%= @prfs_assessment.updated_at.strftime("%H:%M") %>

  <% if current_clinician %>
    <span class="pull-right">
    <%= link_to "Delete", prfs_assessment_path, method: :delete, data: {confirm: 'Are you sure you want to delete'}, class: 'btn btn-u btn-success' %>
    </span>
  <% end %>
</h4>

<head>
   <script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
    
          <div id="ex0"></div>
    <script type="text/javascript">
    setTimeout(function(){google.load('visualization', '1', {'callback':'drawChart()', 'packages':['corechart']})}, 1000);


    function drawChart() {

      var data = google.visualization.arrayToDataTable([
         [' ', 'Score', { role: 'style' }],
         ['Activity and Function', <%= @prfs_assessment.activity_and_function %>, '#3498db' ],
      ]);

      var options = {
        // chartArea:{left:20,top:0,width:'50%',height:'75%'}
        width: 1000,
        height: 563,
        hAxis: {
          title: "Patient's Activity Level",
          gridlines: {count: 4}
        },
        vAxis: {
          title: 'Score (scale of 0-4)'
          // {minValue: 0}
          // viewWindowMode:'explicit',
          // viewWindow:{
          //   max:4,
          //   min:0
        }
      };

      var chart = new google.visualization.ColumnChart(
        document.getElementById('ex0'));

      chart.draw(data, options);
    }
    </script>

<div class="row">
  <div class="col-md-6 comment">
    <h2>Overall Comment</h2>
    <p>
      <%= @prfs_assessment.prfs_comment %>
    </p>
  </div>
</div>

<!--=== Content Part ===-->
<div class="container content">
    <div class="row">
        

        <!-- Begin Content -->
        <div class="col-md-9">
            <!--Basic Table-->
            <div class="panel panel-blue">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-tasks"></i> Score</h3>
                </div>
                <div class="panel-body">
                    <p>The Patient Reported Functional Status (PRFS) tool is a tool completed by patients that assesses their functional status, or activity levels. They are prompted to complete this tool after they have completed their ESAS (Edmonton Symptom Assessment System). Patients are asked to rate their general activity level over the past month by selecting one answer out of five different response options.</p>
                </div>                                      
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="hidden-sm">Score</th>
                            <th>Comment</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="hidden-sm"><%= @prfs_assessment.activity_and_function %></td>
                            <td><%= @prfs_assessment.prfs_comment %></td>
                            <% if (@prfs_assessment.activity_and_function.between?(1, 2)) %>
                              <td><span class="label label-success">Low</span></td>
                            <% else %>
                              <% if (@prfs_assessment.activity_and_function.between?(3, 4)) %>
                                <td><span class="label label-warning">Moderate</span></td>
                              <% else %>
                                <% if (@prfs_assessment.activity_and_function.between?(5, 5)) %>
                                  <td><span class="label label-danger">High!</span></td>
                                <% else %>
                                  <td><span class="label label-info">None</span></td>
                                <% end %>
                              <% end %>
                            <% end %>
                        </tr>
                        
                    </tbody>
                </table>
            </div>
            <!--End Basic Table-->
        </div>
        <!-- End Content -->
    </div>          
</div><!--/container-->     
<!--=== End Content Part ===-->


<div class="container content">
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-blue margin-bottom-40">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-tasks"></i> Information</h3>
        </div>
        <table class="table table-striped table-bordered">
          <tr>
            <td><strong>Care giver name</strong></td>
            <% if @care_giver == nil %>
              <% if @prfs_assessment.clinician_completed == true %>
                <td><%= link_to @prfs_assessment.clinician.full_name, clinician_path(@prfs_assessment.clinician.id) %></td>
              <% else %>
               <td>Self completed</td>
              <% end %>
            <% else %>
              <td><%= link_to @care_giver.full_name, care_giver_path(@care_giver) %></td>
            <% end %>
          </tr>
          <tr>
            <td><strong>Care giver relation</strong></td>
            <% if @care_giver == nil %>
              <% if @prfs_assessment.clinician_completed == true %>
                <td><%= @prfs_assessment.clinician.occupation.name %></td>
              <% else %>
                <td> </td>
              <% end %>
            <% else %>
              <td><%= @care_giver.inputter.inputter_type %></td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>